theme: jekyll-theme-minimal
title: William Iadarola's Pages
email: wji205@nyu.edu
description: This is a collection of my JavaScript Three.js projects hosted on GitHub's pages feature. Three.js is a JavaScript library and 
application programming interface used to create and display animated 3D computer graphics in a web browser using WebGL. Click any of the links 
to explore some of my projects.
