theme: jekyll-theme-minimal
title: William Iadarola's Pages
email: wji205@nyu.edu
description: This is a collection of my JavaScript projects hosted on GitHub's pages feature. Click any of the links to explore some of my projects.
